languageCode = "en-us"
title = "Spring Cloud Config"
theme = "hugo-theme-bootie-docs"
copyright = "© Copyright Pivotal. All rights reserved."

[params]
  basedir = "/spring-cloud-config"
  mainMenu=["goals", "setup", "instructions", "resources"]
  noCategoryLink = true
  description = ""
