languageCode = "en-us"
title = "Spring Cloud Netflix: Service Discovery"
theme = "docs"
copyright = "© Copyright Pivotal. All rights reserved."

[params]
  basedir = "/spring-cloud-services-spring-cloud-netflix-service-discovery"
  mainMenu=["goals", "setup", "instructions", "resources"]
  noCategoryLink = true
  description = ""
